# SCENIC+ pipeline

For this tutorial, we are processing the medulloblastoma mouse model single cell multiome data from:

[_Shiraishi, R. & Cancila, G. et al. (2024). Cancer-specific epigenome identifies oncogenic hijacking by nuclear factor I family proteins for medulloblastoma progression. Dev. Cell , 59:2302-2319._](https://www.cell.com/developmental-cell/fulltext/S1534-5807(24)00330-7)

This data set contains three samples comprising FACS sorted cells. These cells reflect the progression from healthy precursors to tumor cells:

1. Ptch1GNP: granule neuron precursors, P7
2. PNC: preneoplastic cells, P28
3. Tumor: tumor cells, adult mice

Data was downloaded from the Gene Expression Omnibus:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE240362

The `GSE240362_RAW.tar` file contains the raw gene expression counts files in HDF5 format (.h5) and ATAC fragment files. This is the typical output you would obtain from the [10X Genomics Cellranger software](https://www.10xgenomics.com/support/software/cell-ranger/latest/getting-started/cr-what-is-cell-ranger).

The ATAC modality (fragment files) were processed with _pycisTopic_ and gene expression (.5) was processed with _Scanpy_. In addition, _cisTarget_ transcription factor binding site motif databases were generated. The SCENIC+ pipelines was then used to infer eRegulon. To see how the processing was done, see the following notebooks:

* [scanpy_rna_processing.ipynp](https://github.com/heckern/2026_ebi_workshop_scenicplus/scanpy_rna_processing.ipynp)
* [pycistopic_atac_processing.ipynp](https://github.com/heckern/2026_ebi_workshop_scenicplus/pycistopic_atac_processing.ipynp)
* [pycistarget_tfmotif_database.ipynp](https://github.com/heckern/2026_ebi_workshop_scenicplus/pycistarget_tfmotif_database.ipynp)

For more details on SCENIC+, have a look at:

* [_Bravo González-Blas, C., De Winter, S., Hulselmans, G., Hecker, N., Matetovici, I., Christiaens, V., ... & Aerts, S. (2023). SCENIC+: single-cell multiomic inference of enhancers and gene regulatory networks. Nat. Methods, 20:1355-1367._](https://www.nature.com/articles/s41592-023-01938-4)
* [SCENIC+ documentation](https://scenicplus.readthedocs.io/en/latest/)

This notebooks shows how the SCENIC+ pipeline was run.

## Configuration

The SCENIC+ pipeline is a Snakemake pipeline that uses a configuration file in YAML format as input.

In [1]:
import os

parentdir = '/storage/nhecker/embl/GSE240362/scenicplus_mm10'

os.makedirs(parentdir, exist_ok = True)

The `init_snakemake` command creates the Snakemake folder structure and initial `config.yaml` file.

In [2]:
! export PATH=$PATH:/home/nikolai/.conda/envs/scenicplus/bin; scenicplus init_snakemake --out_dir /storage/nhecker/embl/GSE240362/scenicplus_mm10

/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
2026-02-17 18:00:52,300 SCENIC+      INFO     Creating snakemake folder in: /storage/nhecker/embl/GSE240362/scenicplus_mm10

We create a helper function to view the files in the folder.

In [3]:
import os

def list_files(startpath):
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        for f in files:
            print('{}{}'.format(subindent, f))

In [4]:
list_files('/storage/nhecker/embl/GSE240362/scenicplus_mm10')

scenicplus_mm10/
    Snakemake/
        workflow/
            Snakefile
        config/
            config.yaml

We create an output and a temporary directory that will be used by the SCENIC+ pipeline.

In [5]:
tempdir = '/storage/nhecker/embl/GSE240362/scenicplus_mm10/temp'
outdir = '/storage/nhecker/embl/GSE240362/scenicplus_mm10/out'

os.makedirs(tempdir, exist_ok = True)
os.makedirs(outdir, exist_ok = True)

As a convenient way to modify the config file, we read it into dictionary using the `yaml` package.

In [6]:
import yaml

path_config = "/storage/nhecker/embl/GSE240362/scenicplus_mm10/Snakemake/config/config.yaml"

with open(path_config) as stream:
    dict_config = yaml.safe_load(stream)

In [7]:
dict_config.keys()

dict_keys(['input_data', 'output_data', 'params_general', 'params_data_preparation', 'params_motif_enrichment', 'params_inference'])

We have to specify the cisTopic object, gene expression anndata object, region set folders, pycisTarget database files, and motif annotation files as input for the pipeline.

In [8]:
dict_config['input_data']

{'cisTopic_obj_fname': '',
 'GEX_anndata_fname': '',
 'region_set_folder': '',
 'ctx_db_fname': '',
 'dem_db_fname': '',
 'path_to_motif_annotations': ''}

In [9]:
dict_config['input_data'] = {
    'cisTopic_obj_fname': '/storage/nhecker/embl/GSE240362/pycistopic_mm10/cistopic_obj.pkl',
    'GEX_anndata_fname': '/storage/nhecker/embl/GSE240362/scanpy/rna_medulloblastoma.h5ad',
    'region_set_folder': '/storage/nhecker/embl/GSE240362/pycistopic_mm10/region_sets',
    'ctx_db_fname': '/storage/nhecker/embl/GSE240362/cistargetdb_mm10/GSE240362_1kb_bg_with_mask.regions_vs_motifs.rankings.feather',
    'dem_db_fname': '/storage/nhecker/embl/GSE240362/cistargetdb_mm10/GSE240362_1kb_bg_with_mask.regions_vs_motifs.scores.feather',
    'path_to_motif_annotations': '/storage/nhecker/resources/cistarget_motif_db/v10nr_clust_public/snapshots/motifs-v10-nr.mgi-m0.00001-o0.0.tbl'
}

Additional config parameters that might have to be adjusted is the number of CPUs and the temp directory.

In [10]:
dict_config['params_general']

{'temp_dir': '', 'n_cpu': 40, 'seed': 666}

In [11]:
tempdir = '/storage/nhecker/embl/GSE240362/scenicplus_mm10/temp'

dict_config['params_general']['n_cpu'] = 32
dict_config['params_general']['temp_dir'] = tempdir

As we are using an older version the mouse genome (mm10). We have to make sure to specify a matching ENSEMBL biomart host for this genome version. This can be changed in the `params_data_preparation` section.

In [12]:
dict_config['params_data_preparation']

{'bc_transform_func': '"lambda x: f\'{x}\'"',
 'is_multiome': True,
 'key_to_group_by': '',
 'nr_cells_per_metacells': 10,
 'direct_annotation': 'Direct_annot',
 'extended_annotation': 'Orthology_annot',
 'species': 'hsapiens',
 'biomart_host': 'http://www.ensembl.org',
 'search_space_upstream': '1000 150000',
 'search_space_downstream': '1000 150000',
 'search_space_extend_tss': '10 10'}

The search space space specifies the distance to between transcription start site (TSS) and potential enhancer regions that SCENIC+ should consider for linking regions to genes.

In [13]:
dict_config['params_data_preparation']['biomart_host'] = 'http://aug2020.archive.ensembl.org'

The `params_motif_enrichment` contains parameters related to selecting regions and predicted motifs to be considered by SCENIC+.

In [14]:
dict_config['params_motif_enrichment']

{'species': 'homo_sapiens',
 'annotation_version': 'v10nr_clust',
 'motif_similarity_fdr': 0.001,
 'orthologous_identity_threshold': 0.0,
 'annotations_to_use': 'Direct_annot Orthology_annot',
 'fraction_overlap_w_dem_database': 0.4,
 'dem_max_bg_regions': 500,
 'dem_balance_number_of_promoters': True,
 'dem_promoter_space': 1000,
 'dem_adj_pval_thr': 0.05,
 'dem_log2fc_thr': 1.0,
 'dem_mean_fg_thr': 0.0,
 'dem_motif_hit_thr': 3.0,
 'fraction_overlap_w_ctx_database': 0.4,
 'ctx_auc_threshold': 0.005,
 'ctx_nes_threshold': 3.0,
 'ctx_rank_threshold': 0.05}

Potentially, the `dem_adj_pval_thr` has to be relaxed in the case the pipeline does not successfully complete due to the lack of enriched regions.

In [15]:
dict_config['params_motif_enrichment']['dem_adj_pval_thr'] = 0.5

We change the species here form human to mouse.

In [16]:
dict_config['params_motif_enrichment']['species'] = 'mus_musculus'

In [17]:
dict_config['params_data_preparation']['species'] = 'mmusculus'

For specifying output files, we append the output folder name to the default file names.

In [18]:
outdir = '/storage/nhecker/embl/GSE240362/scenicplus_mm10/out'

for key, file in dict_config['output_data'].items():
    dict_config['output_data'][key] = outdir + '/' + file

After modifying the values in the dictionary, we save it as YAML file.

In [19]:
path_config = "/storage/nhecker/embl/GSE240362/scenicplus_mm10/Snakemake/config/config.yaml"

with open(path_config, 'w') as file:
    yaml.dump(dict_config, file, default_flow_style=False)

In [20]:
! cat /storage/nhecker/embl/GSE240362/scenicplus_mm10/Snakemake/config/config.yaml

input_data:
  GEX_anndata_fname: /storage/nhecker/embl/GSE240362/scanpy/rna_medulloblastoma.h5ad
  cisTopic_obj_fname: /storage/nhecker/embl/GSE240362/pycistopic_mm10/cistopic_obj.pkl
  ctx_db_fname: /storage/nhecker/embl/GSE240362/cistargetdb_mm10/GSE240362_1kb_bg_with_mask.regions_vs_motifs.rankings.feather
  dem_db_fname: /storage/nhecker/embl/GSE240362/cistargetdb_mm10/GSE240362_1kb_bg_with_mask.regions_vs_motifs.scores.feather
  path_to_motif_annotations: /storage/nhecker/resources/cistarget_motif_db/v10nr_clust_public/snapshots/motifs-v10-nr.mgi-m0.00001-o0.0.tbl
  region_set_folder: /storage/nhecker/embl/GSE240362/pycistopic_mm10/region_sets
output_data:
  AUCell_direct: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/AUCell_direct.h5mu
  AUCell_extended: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/AUCell_extended.h5mu
  chromsizes: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/chromsizes.tsv
  cistromes_direct: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/cistromes_direct.h5ad
  cistromes_extended: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/cistromes_extended.h5ad
  combined_GEX_ACC_mudata: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/ACC_GEX.h5mu
  ctx_result_fname: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/ctx_results.hdf5
  dem_result_fname: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/dem_results.hdf5
  eRegulons_direct: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/eRegulon_direct.tsv
  eRegulons_extended: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/eRegulons_extended.tsv
  genome_annotation: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/genome_annotation.tsv
  output_fname_ctx_html: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/ctx_results.html
  output_fname_dem_html: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/dem_results.html
  region_to_gene_adjacencies: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/region_to_gene_adj.tsv
  scplus_mdata: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/scplusmdata.h5mu
  search_space: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/search_space.tsv
  tf_names: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/tf_names.txt
  tf_to_gene_adjacencies: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/tf_to_gene_adj.tsv
params_data_preparation:
  bc_transform_func: '"lambda x: f''{x}''"'
  biomart_host: http://aug2020.archive.ensembl.org
  direct_annotation: Direct_annot
  extended_annotation: Orthology_annot
  is_multiome: true
  key_to_group_by: ''
  nr_cells_per_metacells: 10
  search_space_downstream: 1000 150000
  search_space_extend_tss: 10 10
  search_space_upstream: 1000 150000
  species: mmusculus
params_general:
  n_cpu: 32
  seed: 666
  temp_dir: /storage/nhecker/embl/GSE240362/scenicplus_mm10/temp
params_inference:
  gsea_n_perm: 1000
  min_regions_per_gene: 0
  min_target_genes: 10
  order_TFs_to_genes_by: importance
  order_regions_to_genes_by: importance
  quantile_thresholds_region_to_gene: 0.85 0.90 0.95
  region_to_gene_correlation_method: SR
  region_to_gene_importance_method: GBM
  rho_threshold: 0.05
  tf_to_gene_importance_method: GBM
  top_n_regionTogenes_per_gene: 5 10 15
  top_n_regionTogenes_per_region: ''
params_motif_enrichment:
  annotation_version: v10nr_clust
  annotations_to_use: Direct_annot Orthology_annot
  ctx_auc_threshold: 0.005
  ctx_nes_threshold: 3.0
  ctx_rank_threshold: 0.05
  dem_adj_pval_thr: 0.5
  dem_balance_number_of_promoters: true
  dem_log2fc_thr: 1.0
  dem_max_bg_regions: 500
  dem_mean_fg_thr: 0.0
  dem_motif_hit_thr: 3.0
  dem_promoter_space: 1000
  fraction_overlap_w_ctx_database: 0.4
  fraction_overlap_w_dem_database: 0.4
  motif_similarity_fdr: 0.001
  orthologous_identity_threshold: 0.0
  species: mus_musculus

## Preparing the genome and genome annotation

To avoid issues during running the pipelines, it is a good idea to prepare the genome annotation and chromosome sizes files in advance.

In [21]:
os.chdir(f"{parentdir}/Snakemake")

In [22]:
! pwd

/storage/nhecker/embl/GSE240362/scenicplus_mm10/Snakemake

We can use `download_genome_annotations` command to obtain the initial files.

In [23]:
! export PATH=$PATH:/home/nikolai/.conda/envs/scenicplus/bin; scenicplus prepare_data download_genome_annotations

/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
usage: scenicplus prepare_data download_genome_annotations [-h] --species
                                                           SPECIES
                                                           --genome_annotation_out_fname
                                                           GENOME_ANNOTATION_OUT_FNAME
                                                           --chromsizes_out_fname
                                                           CHROMSIZES_OUT_FNAME
                                                           [--biomart_host BIOMART_HOST]
                                                           [--do_not_use_ucsc_chromosome_style]
scenicplus prepare_data download_genome_annotations: error: the following arguments are required: --species, --genome_annotation_out_fname, --chromsizes_out_fname

Here we have to make sure to specify an ENSEMBL biomart host that matches the mm10 mouse genome assembly that we are using.

In [24]:
! export PATH=$PATH:/home/nikolai/.conda/envs/scenicplus/bin; scenicplus prepare_data download_genome_annotations  --biomart_host http://aug2020.archive.ensembl.org --species mmusculus --genome_annotation_out_fname  /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/genome_annotation.tsv --chromsizes_out_fname /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/chromsizes.tsv

/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
2026-02-17 18:01:03,657 Download gene annotation INFO     Using genome: GRCm38.p6
Could not find Id on https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=genome&term=GRCm38.p6
Returning gene annotation without subestting for assembled chromosomesand converting to UCSC style. Please make sure that the chromosome namesin the returned object match with the chromosome names in the scplus_obj.Chromosome sizes will not be returned
2026-02-17 18:01:04,075 SCENIC+      INFO     Chrosomome sizes was not found, please provide this information manually.
2026-02-17 18:01:04,076 SCENIC+      INFO     Saving genome annotation to: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/genome_annotation.tsv

Next, we convert the gene annotation into the UCSC chromosome style.

In [25]:
import pandas as pd

path_annotation = "/storage/nhecker/embl/GSE240362/scenicplus_mm10/out/genome_annotation.tsv"

dfanno = pd.read_csv(path_annotation, sep ="\t")
dfanno

,Chromosome,Start,End,Strand,Gene,Transcription_Start_Site,Transcript_type
0,MT,14145,15288,+,mt-Cytb,14145,protein_coding
1,MT,13552,14070,-,mt-Nd6,14070,protein_coding
2,MT,11742,13565,+,mt-Nd5,11742,protein_coding
3,MT,10167,11544,+,mt-Nd4,10167,protein_coding
4,MT,9877,10173,+,mt-Nd4l,9877,protein_coding
...,...,...,...,...,...,...,...
55594,CHR_WSB_EIJ_MMCHR11_CTG3,83144420,83148428,+,LT629154.2,83144420,protein_coding
55595,CHR_WSB_EIJ_MMCHR11_CTG3,83254598,83256993,-,LT629154.3,83256993,protein_coding
55596,CHR_WSB_EIJ_MMCHR11_CTG3,83233324,83245134,-,Slfn14,83245134,protein_coding
55597,CHR_WSB_EIJ_MMCHR11_CTG3,83150467,83174093,+,Slfn3,83150467,protein_coding
55598,CHR_WSB_EIJ_MMCHR11_CTG3,83150467,83174093,+,Slfn3,83150470,protein_coding

We specify a helper function to rename the chromosomes.

In [26]:
def rename_chr_to_ucsc(chrom):

    if chrom == 'MT':
        return 'chrM'
    elif chrom == 'X' or chrom == 'Y' or chrom.isdigit():
        return 'chr' + chrom
    else:
        return chrom

In [27]:
dfanno['Chromosome'] = [rename_chr_to_ucsc(chrom) for chrom in dfanno['Chromosome'] ]

In [28]:
import numpy as np

np.unique(dfanno['Chromosome'])

array(['CHR_CAST_EI_MMCHR11_CTG4', 'CHR_CAST_EI_MMCHR11_CTG5',
       'CHR_MG104_PATCH', 'CHR_MG117_PATCH', 'CHR_MG132_PATCH',
       'CHR_MG153_PATCH', 'CHR_MG171_PATCH', 'CHR_MG184_PATCH',
       'CHR_MG190_MG3751_PATCH', 'CHR_MG191_PATCH', 'CHR_MG209_PATCH',
       'CHR_MG3172_PATCH', 'CHR_MG3231_PATCH', 'CHR_MG3251_PATCH',
       'CHR_MG3490_PATCH', 'CHR_MG3496_PATCH', 'CHR_MG3530_PATCH',
       'CHR_MG3561_PATCH', 'CHR_MG3562_PATCH', 'CHR_MG3618_PATCH',
       'CHR_MG3627_PATCH', 'CHR_MG3648_PATCH', 'CHR_MG3656_PATCH',
       'CHR_MG3683_PATCH', 'CHR_MG3686_PATCH', 'CHR_MG3700_PATCH',
       'CHR_MG3714_PATCH', 'CHR_MG3829_PATCH', 'CHR_MG3833_MG4220_PATCH',
       'CHR_MG3836_PATCH', 'CHR_MG3999_PATCH', 'CHR_MG4136_PATCH',
       'CHR_MG4138_PATCH', 'CHR_MG4151_PATCH', 'CHR_MG4180_PATCH',
       'CHR_MG4200_PATCH', 'CHR_MG4211_PATCH', 'CHR_MG4212_PATCH',
       'CHR_MG4213_PATCH', 'CHR_MG4214_PATCH', 'CHR_MG4222_MG3908_PATCH',
       'CHR_MG4243_PATCH', 'CHR_MG4248_PATCH', 'CHR_MG4249_PATCH',
       'CHR_MG4254_PATCH', 'CHR_MG4261_PATCH', 'CHR_MG4264_PATCH',
       'CHR_MG4265_PATCH', 'CHR_MG4266_PATCH', 'CHR_MG4281_PATCH',
       'CHR_MG4288_PATCH', 'CHR_MG4310_MG4311_PATCH', 'CHR_MG51_PATCH',
       'CHR_MG65_PATCH', 'CHR_MG74_PATCH', 'CHR_MG89_PATCH',
       'CHR_MMCHR1_CHORI29_IDD5_1', 'CHR_PWK_PHJ_MMCHR11_CTG1',
       'CHR_PWK_PHJ_MMCHR11_CTG2', 'CHR_PWK_PHJ_MMCHR11_CTG3',
       'CHR_WSB_EIJ_MMCHR11_CTG1', 'CHR_WSB_EIJ_MMCHR11_CTG2',
       'CHR_WSB_EIJ_MMCHR11_CTG3', 'GL456210.1', 'GL456211.1',
       'GL456212.1', 'GL456216.1', 'GL456219.1', 'GL456221.1',
       'GL456233.1', 'GL456350.1', 'GL456354.1', 'JH584292.1',
       'JH584293.1', 'JH584294.1', 'JH584295.1', 'JH584296.1',
       'JH584297.1', 'JH584298.1', 'JH584299.1', 'JH584303.1',
       'JH584304.1', 'chr1', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14',
       'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr2', 'chr3',
       'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chrM', 'chrX',
       'chrY'], dtype=object)

In [29]:
# save annotatiom
dfanno.to_csv(path_annotation, sep="\t")

To prepare the chromosome sizes files for SCENIC+, we have to add column names.

In [30]:
# create chrom sizes
import pandas as pd

path_chromsizes = "/storage/genomes/mm10/mm10.chrom.sizes"

df = pd.read_csv(path_chromsizes, header=None, sep ="\t")
df

                       0          1
0                   chr1  195471971
1                   chr2  182113224
2                   chrX  171031299
3                   chr3  160039680
4                   chr4  156508116
..                   ...        ...
61        chrUn_GL456396      21240
62        chrUn_GL456368      20208
63                  chrM      16299
64  chr4_JH584292_random      14945
65  chr4_JH584295_random       1976

[66 rows x 2 columns]

In [31]:
chromsizes = pd.DataFrame(
    {
        'Chromosome': df[0],
        'Start': 1,
        'End': df[1]
    }
)

chromsizes

              Chromosome  Start        End
0                   chr1      1  195471971
1                   chr2      1  182113224
2                   chrX      1  171031299
3                   chr3      1  160039680
4                   chr4      1  156508116
..                   ...    ...        ...
61        chrUn_GL456396      1      21240
62        chrUn_GL456368      1      20208
63                  chrM      1      16299
64  chr4_JH584292_random      1      14945
65  chr4_JH584295_random      1       1976

[66 rows x 3 columns]

In [32]:
# save to out folder
path_out_chromsizes = dict_config['output_data']['chromsizes']

#chromsizes.to_csv(path_out_chromsizes, sep="\t", index=False)
chromsizes.to_csv(path_out_chromsizes, sep="\t", index=False)

To run the Snakemake pipeline, we simple call the 'snakemake' command. Here we specify the number of CPUs and set the latency to 30 seconds to avoid timeouts for downloading files.

In [ ]:
! export PATH=$PATH:/home/nikolai/.conda/envs/scenicplus/bin; snakemake --cores 32  --latency-wait 30

Assuming unrestricted shared filesystem usage for local execution.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 32
Rules claiming more threads will be scaled down.
Job stats:
job                           count
--------------------------  -------
AUCell_direct                     1
AUCell_extended                   1
all                               1
eGRN_direct                       1
eGRN_extended                     1
get_search_space                  1
motif_enrichment_cistarget        1
motif_enrichment_dem              1
prepare_GEX_ACC_multiome          1
prepare_menr                      1
region_to_gene                    1
scplus_mudata                     1
tf_to_gene                        1
total                            13

Select jobs to execute...
Execute 1 jobs...

[Tue Feb 17 18:01:05 2026]
localrule motif_enrichment_cistarget:
    input: /storage/nhecker/embl/GSE240362/pycistopic_mm10/region_sets, /storage/nhecker/embl/GSE240362/cistargetdb_mm10/GSE240362_1kb_bg_with_mask.regions_vs_motifs.rankings.feather, /storage/nhecker/resources/cistarget_motif_db/v10nr_clust_public/snapshots/motifs-v10-nr.mgi-m0.00001-o0.0.tbl
    output: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/ctx_results.hdf5, /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/ctx_results.html
    jobid: 9
    reason: Missing output files: /storage/nhecker/embl/GSE240362/scenicplus_mm10/out/ctx_results.hdf5
    threads: 32
    resources: tmpdir=/tmp

/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
2026-02-17 18:01:12,003 SCENIC+      INFO     Reading region sets from: /storage/nhecker/embl/GSE240362/pycistopic_mm10/region_sets
2026-02-17 18:01:12,003 SCENIC+      INFO     Reading all .bed files in: DARs_sample
2026-02-17 18:01:12,018 SCENIC+      INFO     Reading all .bed files in: DARs_leiden0_5_rna
2026-02-17 18:01:12,054 SCENIC+      INFO     Reading all .bed files in: DARs_leiden0_5_atac
2026-02-17 18:01:12,095 SCENIC+      INFO     Reading all .bed files in: Topics_otsu
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
/home/nikolai/.conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
2026-02-17 18:01:20,138 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,146 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,173 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,193 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,276 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,289 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,293 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,322 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,330 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,334 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,352 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,352 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,362 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,363 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,411 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,412 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,420 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,424 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,430 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,431 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,432 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,435 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,445 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,460 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,465 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,466 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,476 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,501 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,546 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,574 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,588 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:20,771 cisTarget    INFO     Reading cisTarget database
2026-02-17 18:01:23,716 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_8 which has 3428 regions
2026-02-17 18:01:23,952 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_7 which has 3381 regions
2026-02-17 18:01:23,985 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_6 which has 1586 regions
2026-02-17 18:01:24,021 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_1 which has 2494 regions
2026-02-17 18:01:24,131 cisTarget    INFO     Running cisTarget for DARs_sample_Tumor which has 6233 regions
2026-02-17 18:01:24,295 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_9 which has 4285 regions
2026-02-17 18:01:24,323 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_9 which has 3574 regions
2026-02-17 18:01:24,363 cisTarget    INFO     Running cisTarget for DARs_sample_Ptch1GNP which has 7510 regions
2026-02-17 18:01:24,363 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_0 which has 6129 regions
2026-02-17 18:01:24,433 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_10 which has 4184 regions
2026-02-17 18:01:24,455 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_8 which has 5205 regions
2026-02-17 18:01:24,604 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_2 which has 8303 regions
2026-02-17 18:01:24,609 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_4 which has 9538 regions
2026-02-17 18:01:24,623 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_5 which has 6847 regions
2026-02-17 18:01:24,678 cisTarget    INFO     Running cisTarget for DARs_sample_PNC which has 5729 regions
2026-02-17 18:01:24,695 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_0 which has 6918 regions
2026-02-17 18:01:24,717 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_rna_7 which has 5621 regions
2026-02-17 18:01:24,749 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_5 which has 6598 regions
2026-02-17 18:01:24,878 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_1 which has 2899 regions
2026-02-17 18:01:24,955 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_3 which has 7016 regions
2026-02-17 18:01:25,030 cisTarget    INFO     Running cisTarget for DARs_leiden0_5_atac_6 which has 7442 regions